{{- if .Values.certificate.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ default (include "element-web.fullname" .) (tpl .Values.certificate.name .) }}
spec:
  {{- toYaml .Values.certificate.spec | nindent 2 }}
{{- end }}
