{{- if .Values.ingress.enabled -}}
{{- $fullName := include "element-web.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-http
  labels:
    {{- include "element-web.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`element.rwx.im`)
    middlewares:
    - name: {{ $fullName }}-security-headers
    - name: {{ $fullName }}-https-redirect
    services:
    - name: {{ $fullName }}
      kind: Service
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-https
  labels:
    {{- include "element-web.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`element.rwx.im`)
    middlewares:
    - name: {{ $fullName }}-security-headers
    services:
    - name: {{ $fullName }}
      kind: Service
      port: 80
{{- end }}
