{{- if .Values.ingress.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "element-web.fullname" . }}-security-headers
  labels:
    {{- include "element-web.labels" . | nindent 4 }}
spec:
  headers:
    customFrameOptionsValue: SAMEORIGIN
    contentTypeNosniff: true
    browserXssFilter: true
    contentSecurityPolicy: "frame-ancestors 'none'"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "element-web.fullname" . }}-https-redirect
  labels:
    {{- include "element-web.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
