{{- if .Values.ingress.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "wayback.fullname" . }}-https-redirect
  labels:
    {{- include "wayback.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
